version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: jacobwoffenden/rpmbuilder:latest
    steps:
      - checkout
      - run:
          name: Building RPM
          command: echo lol
          
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
