version: 2.1

orbs:
  diag: fernfernfern/diag@dev:dev

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - diag/start
       
workflows:
  flooooow:
    jobs:
      - build

