version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Building RPM
          command: echo lol

workflows:
  version: 2
  build_workflow:
    triggers:
      - schedule:
          cron: "1 * * * *"
          filters:
            branches:
              only:
                - workflows
    jobs:
      - build
