version: 2
jobs:
  build1:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir lol
      - run:
          name: Building RPM
          command: echo lol > lolfile1
      - store_artifacts:
          path: /lol
  build2:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir lol
      - run:
          name: Building RPM
          command: echo lol > lol/lolfile2
      - store_artifacts:
          path: /lol

workflows:
  version: 2
  build_workflow:
    jobs:
      - build1
      - build2

  schedule_workflow:
    triggers:
      - schedule:
          cron: "* * * 9 *"
          filters:
            branches:
              only:
                - workflows
    jobs:
      - build1
      - build2
