version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Building RPM
          command: echo lol

workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "10 * * * *"
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
